import time

#start
time.sleep(2)
print("you will see some stuff that wil not make some sense, but remember this is fiction and some stuff wont make sence but will be enjoyable.")
name = input("please enter your name: ")
time.sleep(3)
start = input("press ENTER to begin: ")
time.sleep(4)
print ("SC 1")
time.sleep(4)
print ("game starting...")
time.sleep(5)

#chapter 1

print ("chapter 1: the start")
time.sleep(4)
input1 = input("which base should we attack: ")
print ("attacking base " + input1 + "...")
time.sleep(1)
print ("...")
time.sleep(1)
print ("...")
time.sleep(4)
print ("mission succesful")
time.sleep(4)
print ("people badly injured")
time.sleep(4)
input2 = input("Press ENTER to call health support: ")
time.sleep (4)
print ("calling health support")
time.sleep(2)
print ("health support has arrived")
time.sleep(2)
print ("healing...")
time.sleep(1)
print ("...")
time.sleep(1)
print ("...")
time.sleep(1)
print ("...")
time.sleep(4)
print ("all of the people have been successfully healed")
time.sleep(5)
print ("chapter 1 has ended")

#chapter 2

time.sleep(5)
input3 = input("Press ENTER to continue chapter 2: ")
time.sleep(3)
print("chapter 2: Friends or enemies?")
time.sleep(5)
print ("James: Thanks for saving me " + name)
time.sleep(4)
input4 = input("Press ENTER to answer: ")
time.sleep(3)
print (name + ": Your Welcome")
time.sleep(3)
print ("james: is there anything I can do for you?")
time.sleep(3)
input5 = input("Press ENTER to answer: ")
time.sleep(3)
print (name + ": No need, what do you say we go eat huh?")
time.sleep(4)
print("James: sure!")
time.sleep(2)
input6 = input("Press ENTER to go eat: ")
time.sleep(3)
print("...")
time.sleep(3)
print("...")
time.sleep(3)
print("James and you went and ordered there food, but he saw james on his computer. When you asked him what he was doing. He said nothing, he left to the bathroom and you thought of checking his laptop and after checking his laptop...")
time.sleep(3)
input7 = input("Press ENTER to continue: ")
time.sleep(3)
print("you saw he was texting to the enemy spy...")
time.sleep(3)
print("your heart felt like it was out of your body")
time.sleep(3)
print("you felt so betrayed")
time.sleep(1)
print("and by your best friend...")
time.sleep(2)
print("you didnt want to tell him because if he knew he would certenly kill you.")
time.sleep(3)
print("you had an idea")
time.sleep(3)
input8 = input("Press ENTER to listen to more: ")
time.sleep(3)
print("you thought to play along...")
time.sleep(3)
print("you installed a program to his computer")
time.sleep(3)
print("it lets you to know what he is typing and can change what he is texting")
time.sleep(2)
print("and thought that when James would type anything you would tell them the opposite.")
input9 = input("Press ENTER to continue: ")
time.sleep(3)
print("James arrives")
time.sleep(3)
print("you both finish your food and then leave")
time.sleep(2)
input10 = input("Press ENTER to go home: ")
time.sleep(3)
print("you go home...")
time.sleep(3)
print("at night you think about James...")
time.sleep(3)
print("you still hear your heart beating...")
time.sleep(3)
input11 = input("Press ENTER to continue")
time.sleep(3)
print("you can't sleep...")
time.sleep(3)
print("you are still thining about James...")
time.sleep(3)
print("you are trying to get it all together and trying to sleep...")
input12 = input("Press ENTER to sleep: ")
time.sleep(3)
print("you finally slept...")
time.sleep(3)
print("...")
time.sleep(1)
print("...")
time.sleep(1)
print("...")
time.sleep(4)
print("ding ding ding!!")
time.sleep(2)
print("you wake up... there is a nock on the door...")
time.sleep(2)
print("you open it and..")
time.sleep(3)
input13 = input("Press ENTER to continue: ")
time.sleep(2)
print("it's james.")
time.sleep(2)
print("he is holding a nife.")
time.sleep(2)
print("he is about to kill you...")
time.sleep(2)
input14 = input("Press ENTER to continue: ")
time.sleep(3)
print("ahhhhhhhhhhhh")
time.sleep(2)
print("you wake up...")
time.sleep(2)
print(name + ": Oh my GOD, what the hell, it was a dream.")
time.sleep(2)
print("ding diong")
time.sleep(2)
print("you remember your dream")
time.sleep(2)
print("you hold your breath and open the door...")
time.sleep(2)
print(name + ": Hi!")
time.sleep(2)
print("its james!")
time.sleep(2)
print("james: Hi")
time.sleep(2)
input15 = input("Press ENTER to answer: ")
time.sleep(2)
print(name + ": Hi, How are you?")
time.sleep(2)
print("james: I am fine how are you?")
time.sleep(5)
input16 = input("Press ENTER to answer: ")
time.sleep(2)
print("James: soo can you tell me where is your HQ? just asking you know")
time.sleep(2)
print("James is an enemy spy...")
time.sleep(2)
print("should you tell him...")
time.sleep(2)
print("you certenly know what he is gonna do...")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(3)
print(name + ": umm I actually forgot, haha. I am really tired today so I will talk to you tommoro.")
time.sleep(2)
print("...")
print("James: ohh ok no problem")
time.sleep(2)
print("you shut the door")
time.sleep(2)
input17 = input("Press ENTER to continue: ")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(2)
print("you think what to do know")
time.sleep(2)
input18 = input("Press ENTER to continue: ")
time.sleep(2)
print("You think of telling the leader...")
time.sleep(2)
print("you know he would be banned from this country...")
time.sleep(2)
print("but you have no choice")
time.sleep(2)
print("you think of telling him...")
time.sleep(2)
print("but again... you know he will for sure kill you..")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(2)
input19 = input("Press ENTER to continue: ")
time.sleep(2)
print("He thought of telling him...")
time.sleep(2)
print("if he would kill him, he knew in his heart he would never kill or hurt him...")
time.sleep(4)
print("He has been your friend when you were 5")
time.sleep(4)
print("and know we are 25, amd still friends")
time.sleep(4)
print("And if he even kills me, what is the point to live, I got killed by the friend who was the only person I loved and trusted.")
time.sleep(4)
print("My parents died when I was 16, and then I got adopted, but I didnt love them, I hated them...")
time.sleep(4)
input20 = input("Press ENTER to continue: ")
time.sleep(4)
print("the only reason why they adopted me was because they wanted to have a worker, and for $0")
time.sleep(4)
print("So when I was 18 I left them, and to this day I still hate them for only feeding me once and for making me work 24/7.")
time.sleep(4)
print("James is the person I love the most, so It doesnt matter if I die or not cause I will have no one to love and care about.")
time.sleep(4)
input21 = input("Press ENTER to continue: ")
time.sleep(2)
print("you spend your normal day...")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(3)
print("you go to bed...")
time.sleep(2)
print("...")
time.sleep(2)
print("and think about James...")
time.sleep(3)
print("you think to yourself this might be my last day...")
time.sleep(4)
print("...")
time.sleep(2)
print(name + ": Let me sleep, this might be my last one...")
time.sleep(4)
print("zzz")
time.sleep(2)
print("zzz")
time.sleep(2)
print("zzz")
time.sleep(2)
print("its day time...")
time.sleep(2)
print("you hear the bell...")
time.sleep(2)
print("you start hearing your heart beating...")
time.sleep(4)
print("just like you did when you remembered James was working for the enemy spy...")
time.sleep(4)
print("door rings again...")
time.sleep(2)
print("you open the door...")
time.sleep(2)
input22 = input("Press ENTER to continue: ")
time.sleep(2)
print("James: Hi!")
time.sleep(2)
input23 = input("Press ENTER to answer: ")
time.sleep(2)
print(name + ": Oh hi!")
time.sleep(2)
print("James: Hello,soo do you know where the HQ is?")
time.sleep(4)
input24 = input("Press ENTER to answer: ")
time.sleep(2)
print(name + ": oh yeh, about that...")
time.sleep(4)
print(name + ": I actually wante-")
time.sleep(4)
print("James: actually its fine.")
time.sleep(4)
print("James: I wanted to tell you something...")
time.sleep(4)
input25 = input("Press ENTER to answer: ")
time.sleep(2)
print(name + ": yeh, what is it?")
time.sleep(4)
print("James: I wanted to give you something...")
time.sleep(4)
print("he gives you a piece of paper...")
time.sleep(4)
print("James: You were a good friend.")
time.sleep(4)
print("he runs in his car and leave...")
time.sleep(4)
print("You are just standing there, trying to process what happened...")
time.sleep(4)
print("you open the paper and...")
time.sleep(4)
input26 = input("Press ENTER to continue: ")
time.sleep(2)
print("...")
time.sleep(2)
print("...")
time.sleep(3)
print("the note said: Hi, " + name + ".")
time.sleep(3)
print("if you are reading this I am a week away from dieing...")
time.sleep(3)
print("no need to come after me...")
time.sleep(2)
print("you see " + name + ", I was working for the enemy government...")
time.sleep(3)
print("I had no choice...")
time.sleep(3)
print("thats why I asked you where your HQ is.")
time.sleep(3)
print("But I didnt want to...")
time.sleep(3)
print("they said they would kill me if I didnt lisen to them...")
time.sleep(4)
print("So for you " + name + ", I sacrificed my life for you.")
time.sleep(4)
print("just as you would sacrifice your life for me...")
time.sleep(3)
print("soo, good luck my friend. My best friend...")
time.sleep(6)
print("...")
time.sleep(3)
print("...")
time.sleep(3)
input27 = input("Press ENTER to continue...: ")
time.sleep(3)
print(name + " stood there, it was like he was in coma.You couldnt move.")
time.sleep(5)
print("after that...")
time.sleep(2)
print("You didnt know what to do...")
time.sleep(3)
input28 = input("Press ENTER to continue...: ")
time.sleep(3)
print("you slept...")
time.sleep(4)
print("that was it...")
time.sleep(3)
print("the story of " + name + " was finished.")
time.sleep(5)
print("chapter 2 has ended...")
time.sleep(3)
input29 = input("Press ENTER to continue chapter 3: ")